version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - dist/**/*                       # Весь результат билда
    - appspec.yml                     # Для CodeDeploy
    - scripts/**/*                    # Скрипты для CodeDeploy
  base-directory: '.'                 # Взять все из корневой папки билда
