apiVersion: v1
kind: Service
metadata:
  name: random-character-ui
spec:
  selector:
    app: random-character-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  # type: ClusterIP # можно вовсе не указывать, ClusterIP — это default!